export const BlogData = [
  {
    id: 1,
    date: "September 4, 2023",
    customer: "By Bosslyn",
    title: "How to choose Quality Device",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id fuga vel nesciunt eos",
    cover: "blog1.jpg",
  },
  {
    id: 2,
    date: "September 4, 2023",
    customer: "By Bosslyn",
    title: "How to choose Quality Device",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id fuga vel nesciunt eos",
    cover: "blog2.webp",
  },
  {
    id: 3,
    date: "September 4, 2023",
    customer: "By Bosslyn",
    title: "How to choose Quality Device",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id fuga vel nesciunt eos",
    cover: "blog3.jpg",
  },
  {
    id: 4,
    date: "September 4, 2023",
    customer: "By Bosslyn",
    title: "How to choose Quality Device",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id fuga vel nesciunt eos",
    cover: "blog5.jpg",
  },
  {
    id: 5,
    date: "September 4, 2023",
    customer: "By Bosslyn",
    title: "How to choose Quality Device",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id fuga vel nesciunt eos",
    cover: "blog5.jpeg",
  },
  {
    id: 6,
    date: "September 4, 2023",
    customer: "By Bosslyn",
    title: "How to choose Quality Device",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id fuga vel nesciunt eos",
    cover: "blog7.jpg",
  },
  {
    id: 7,
    date: "September 4, 2023",
    customer: "By Bosslyn",
    title: "How to choose Quality Device",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id fuga vel nesciunt eos",
    cover: "blog8.jpg",
  },
  {
    id: 8,
    date: "September 4, 2023",
    customer: "By Bosslyn",
    title: "How to choose Quality Device",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id fuga vel nesciunt eos",
    cover: "recent3.jpg",
  },
];
